---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"
    
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

#- hosts: centos
#  become: true
#  roles:
#    - nagios_centos

#- hosts: centos
#  become: true
#  roles:
#    - prometheus_centos

#- hosts: centos
#  become: true
#  roles:
#    - elasticstack_centos

#- hosts: centos
#  become: true
#  roles:
#    - influxdb_centos

#- hosts: centos
#  become: true
#  roles:
#    - grafana_centos

#- hosts: centos
#  become: true
#  roles:
#    - lampstack_centos

- hosts: ubuntu
  become: true
  roles:
    - nagios_ubuntu

- hosts: ubuntu
  become: true
  roles:
    - prometheus_ubuntu

- hosts: ubuntu
  become: true
  roles:
    - elasticstack_ubuntu

- hosts: ubuntu
  become: true
  roles:
    - influxdb_ubuntu

- hosts: ubuntu
  become: true
  roles:
    - grafana_ubuntu

- hosts: ubuntu
  become: true
  roles:
    - lampstack_ubuntu

